service:
    # Service wide configurations
    name: DefaultService
    multiprocessing: False
    # listen interface (only one possible)
    listen:
      host: 0.0.0.0
      port: 5090
      max_clients: 500
    # define pipleines
    pipelines:
      noop:
        processes:
        - Forwarding: default
        worker: 1
        probability: 100
        output: response

